Taula membre
CREATE TABLE "membre" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nom" VARCHAR NOT NULL , "cognoms" VARCHAR NOT NULL , "correu" VARCHAR, "telefon" VARCHAR)
Taula quotes
CREATE TABLE "quota" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "mes" INTEGER NOT NULL , "quantitat" INTEGER NOT NULL , id_membre INTEGER NOT NULL, FOREIGN KEY (id_membre) REFERENCES membre(ID)  )


